"""Monnify API constants — https://developers.monnify.com/"""

# Inbound: reserved account funding (transaction completion webhook — flat payload)
PAYMENT_STATUS_PAID = "PAID"
PRODUCT_TYPE_RESERVED_ACCOUNT = "RESERVED_ACCOUNT"

# Outbound disbursement webhook event types (wrapped in eventType / eventData)
DISBURSEMENT_SUCCESS = "SUCCESSFUL_DISBURSEMENT"
DISBURSEMENT_FAILED = "FAILED_DISBURSEMENT"
DISBURSEMENT_REVERSED = "REVERSED_DISBURSEMENT"

DISBURSEMENT_WEBHOOK_EVENTS = frozenset(
    {DISBURSEMENT_SUCCESS, DISBURSEMENT_FAILED, DISBURSEMENT_REVERSED}
)

DISBURSEMENT_STATUS_SUCCESS = "SUCCESS"
DISBURSEMENT_STATUS_COMPLETED = "COMPLETED"
DISBURSEMENT_STATUS_FAILED = "FAILED"
DISBURSEMENT_STATUS_REVERSED = "REVERSED"
DISBURSEMENT_STATUS_PENDING = "PENDING"
DISBURSEMENT_STATUS_PENDING_AUTH = "PENDING_AUTHORIZATION"

# Monnify webhook source IP (production) — https://developers.monnify.com/docs/webhooks
MONNIFY_WEBHOOK_IP = "35.242.133.146"
