"""Device sessions with rotating refresh tokens (customers and staff).

Revision ID: 010_auth_sessions
Revises: 009_schema_reconcile
Create Date: 2026-09-23 14:04:05.439492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '010_auth_sessions'
down_revision: Union[str, None] = '009_schema_reconcile'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('subject_type', sa.Enum('customer', 'staff', name='subjecttype'), nullable=False),
    sa.Column('subject_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_refresh_token_hash', sa.String(length=64), nullable=True),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=40), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_previous_refresh_token_hash'), 'auth_sessions', ['previous_refresh_token_hash'], unique=False)
    op.create_index(op.f('ix_auth_sessions_refresh_token_hash'), 'auth_sessions', ['refresh_token_hash'], unique=True)
    op.create_index('ix_auth_sessions_subject', 'auth_sessions', ['subject_type', 'subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_sessions_subject', table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_refresh_token_hash'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_previous_refresh_token_hash'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    sa.Enum(name='subjecttype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
